// library/React/Templates/spray-art-school/src/components/Navbar.tsx
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import Logo from "./Logo";
import Button from "./Button";

const NAV_LINKS = [
  { label: "Work", to: "/work" },
  { label: "About", to: "/about" },
  { label: "Contact", to: "/contact" },
];

export default function Navbar() {
  const [scrolled, setScrolled] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 12);
    window.addEventListener("scroll", onScroll);
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  return (
    <header
      className={`sticky top-0 z-40 border-b-2 transition-colors ${
        scrolled ? "border-bone/20 bg-ink-black/90 backdrop-blur" : "border-transparent bg-transparent"
      }`}
    >
      <nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4" aria-label="Primary">
        <Logo />

        <ul className="hidden items-center gap-8 font-body text-sm md:flex">
          {NAV_LINKS.map((link) => (
            <li key={link.to}>
              <Link to={link.to} className="transition-colors hover:text-neon-green">
                {link.label}
              </Link>
            </li>
          ))}
        </ul>

        <div className="hidden md:block">
          <Button variant="standard">Sign up</Button>
        </div>

        <button
          type="button"
          className="text-2xl md:hidden"
          aria-label={menuOpen ? "Close menu" : "Open menu"}
          aria-expanded={menuOpen}
          onClick={() => setMenuOpen((open) => !open)}
        >
          {menuOpen ? "✕" : "☰"}
        </button>
      </nav>

      {menuOpen && (
        <ul className="flex flex-col gap-4 border-t-2 border-bone/20 bg-ink-black px-6 py-6 font-body text-sm md:hidden">
          {NAV_LINKS.map((link) => (
            <li key={link.to}>
              <Link to={link.to} onClick={() => setMenuOpen(false)}>
                {link.label}
              </Link>
            </li>
          ))}
          <li>
            <Button variant="standard" className="w-full">
              Sign up
            </Button>
          </li>
        </ul>
      )}
    </header>
  );
}

// Vue/Components/Navigation/navbar/Navbar.vue
<script setup>
defineOptions({ name: 'Navbar' })
import { ref } from 'vue'
defineProps({ links: { type: Array, default: () => [] }, brand: { type: String, default: 'Brand' } })
const open = ref(false)
</script>
<template><header class="border-b border-slate-200 bg-white/95 backdrop-blur dark:border-slate-800 dark:bg-slate-950/95"><nav class="mx-auto flex min-h-16 max-w-7xl items-center justify-between gap-4 px-4 sm:px-6 lg:px-8"><a href="#" class="shrink-0 text-base font-semibold tracking-tight text-slate-950 dark:text-white">{{ brand }}</a><div class="hidden items-center gap-1 md:flex"><a v-for="link in links" :key="link.href" :href="link.href" class="rounded-lg px-3 py-2 text-sm text-slate-600 transition hover:bg-slate-100 hover:text-slate-950 dark:text-slate-400 dark:hover:bg-slate-900 dark:hover:text-white">{{ link.label }}</a></div><button type="button" class="rounded-lg p-2 text-slate-700 md:hidden dark:text-slate-300" aria-label="Toggle navigation" @click="open=!open">☰</button></nav><div v-if="open" class="border-t border-slate-200 px-4 py-3 md:hidden dark:border-slate-800"><a v-for="link in links" :key="link.href" :href="link.href" class="block rounded-lg px-3 py-3 text-sm text-slate-700 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-900">{{ link.label }}</a></div></header></template>
